language: java
jdk:
  - openjdk8
env:
#  - COVERAGE_VAR=0.35
  - COVERAGE_VAR=0.30
script:
  - ./gradlew clean jar
#  - ./gradlew test
after_success:
#  - ./gradlew jacocoTestReport
#  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
before_deploy:
  - COVERAGE=${COVERAGE_VAR} ./gradlew test jacocoTestCoverageVerification
deploy:
  provider: script
  script: bash echo "Work in Progress"
