language: java
jdk:
  - openjdk8
env:
#  - COVERAGE_VAR=0.35
  - COVERAGE_VAR=0.30
script:
  - ./gradlew clean jar
#  - ./gradlew test
after_success:
#  - ./gradlew jacocoTestReport
#  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
before_deploy:
  - COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/order check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
  - COVERAGE=0.5 ./gradlew -p ./monolithic/repository/user check

deploy:
  provider: script
  script:
    bash echo "Work in Progress"
