language: java
jdk:
  - openjdk8
env:
  - TESTFOLDER=monolithic/ui
  - TESTFOLDER=monolithic/service/cart
  - TESTFOLDER=monolithic/service/user
  - TESTFOLDER=monolithic/repository/order
  - TESTFOLDER=monolithic/repository/cart
  - TESTFOLDER=monolithic/repository/product
  - TESTFOLDER=monolithic/repository/user

script:
  - ./gradlew clean jar

after_script:
  - if [[( "$TESTFOLDER" == "monolithic/repository/order") || ( "$TESTFOLDER" == "monolithic/repository/user")]]; then
    COVERAGE=0.3 ./gradlew -p ./${TESTFOLDER} check ;
    else
    COVERAGE=0.5 ./gradlew -p ./${TESTFOLDER} check ;
    fi
