language: java
jdk:
  - openjdk8
#env:
#  - COVERAEG_VAR=35
#  - COVERAEG_VAR=30
script:
  - ./gradlew clean jar
#  - ./gradlew test
after_success:
#  - ./gradlew jacocoTestReport
#  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
before_deploy:
  - COVERAGE= 0.3 ./gradlew test jacocoTestCoverageVerification
deploy:
  script: echo "Work in Progress"
