services:
- docker
env:
  matrix:
  - DOCKER_LOGIN=mangeshkdocker
  global:
    secure: qX0Bcpg9beGGG+69y4nwHjUbAhDUbd945g5NdlpzOxu2txm3tu/yQNxfwh+iNsYupWpZyO6EoOy+Wd0UmGy19j+W/4PeM76K053BtLPDFtA+trPs0TwkAetCK6HRg31on9yf1I0Z7ROV3p89dv4IQSor56cbjSsXipUvJj+On/5qURzxX/mIRIpMgotL4J2ABfvcRx19UfT7QmWN+hAS7DcQQfRy5YWcV/H7j0o+f+44AjcrFjqaWhPAsvsfQ0tVFeynkPb6WaO4sb/ItF5kFVAh192QvRVDE/typW5Tdf9xGRTfTn53GrRBeLT/6PxKuvsCaEY7dg3o6GLCTvT0PKNyrd71MPRABa0PyxhViZPjwUGzBKsHR4ZiASFXcDcuX6NRWUmqKZJIEL/flmLicplbW8ABqEFq9A71Qa0DeiVdxH9bG8rzch2b5ylshVxi7QgyWC87GE3Irzz+zEqMa3sZrixcktxjFhXPOqzoPTEtzrElG8QEptED0zJ3fd/AHWbu+e4Ln7IuO5yZizZbhI261mZvJY42qRMq0zaWFOSoLWqFb4AjgXmiuMVFSRpELNAmmbzqTH4rvFNUcrZErwCGNiaG5KVBzFgsz6V1DFabOnYJPjzUzDn1iaVka8hKUChqDmIbnwAMgkFkiIvUAjpnTbmQXkGVXRD3n4SvAJQ=
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
