language: java
jdk:
  - openjdk8
script:
  - ./gradlew clean jar
  - ./gradlew test
after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
before_deploy:
  - ./gradlew test jacocoTestCoverageVerification
deploy:
  script: echo "WIP"
